@baseUrl = http://localhost:8000
### Find all measuring units
GET {{baseUrl}}/api/measuring-units?include=orderItems
###


### Find  measuring units by id
GET {{baseUrl}}/api/measuring-units/1
###


### Create   measuring units
POST {{baseUrl}}/api/measuring-units
Content-Type: application/json

{
"name": "gallon1",
"description": "120 centiliters"

}
###

### Update   measuring units
PATCH  {{baseUrl}}/api/measuring-units/68
Content-Type: application/json

{
"name": "Gallon",
"description": "110 centillitre",
"convertTo": "cl"
}
###


### Delete  measuring units by id
DELETE  {{baseUrl}}/api/measuring-units/69
###
