@baseUrl = http://localhost:8000
### Find all room types
GET {{baseUrl}}/api/room-types?include=rooms
###


### Find room type by id
GET {{baseUrl}}/api/room-types/2
###

### Create room type
POST {{baseUrl}}/api/room-types/
Content-Type: application/json

{
"name": "VIP Elite",
"basePrice": 2000,
"description": "The best room"

}
###

### update room type
PATCH {{baseUrl}}/api/room-types/7
Content-Type: application/json

{
"name": "VIP1",
"basePrice": 1000,
"description": "The best room"
}
###


###
DELETE {{baseUrl}}/api/room-types/7
###

