@baseUrl = http://localhost:8000
### Find all rooms
GET {{baseUrl}}/api/rooms?include=roomStatus 
###


### Find room by id
GET {{baseUrl}}/api/rooms/246e6ee1-febd-4e2f-997e-0462edb6d03b
###




### Create room
POST {{baseUrl}}/api/rooms/
Content-Type: application/json

{
"roomNumber": 15,
"roomTypeId": 4
}
###

### update room
PATCH {{baseUrl}}/api/rooms/246e6ee1-febd-4e2f-997e-0462edb6d03b
Content-Type: application/json

{

"roomTypeId": 4,
"roomStatusId": 3,
"roomNumber": 11
}
###

##delete room
DELETE {{baseUrl}}/api/rooms/313743be-9571-46e2-a4cd-e88cc50831c5

